Feature/second milestone
codesalley/ror-social-scaffold pull request #4
Opened 2021-03-19 14:55 UTC by juxsalley

## features 
> user can invite other users 
> user can accept or reject invites 
> post, comment and like posts.

2021-03-19 18:52 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @juxsalley :clap: :clap:
#### You have done a good job :+1: the models are well implemented :muscle:
#### However, some requirements are missing/not implemented correctly. Check my comments below :point_down:

#### 1) App Behaviour:
 - There should be a button to invite a user to friendship on the user single show page
 - Posts timeline should include posts written by logged-in user and their friends

#### 2) Test:
 - Add integration tests

#### 3) View & Logic:
 - There should be NO application logic in the views use the helper method instead. Check these links for details [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code), [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers),


#### _Reviewed by Temitayo Adeleke_

2021-03-19 18:52 UTC, lekegitrepo commented on app/views/friendships/_all_friends.html.erb
> +<% end %> <% end %>
- Remove logic from the view

2021-03-19 18:52 UTC, lekegitrepo commented on app/views/friendships/_received_requests.html.erb
> +<% end %>
- Remove logic from the view

2021-03-19 18:52 UTC, lekegitrepo commented on app/views/layouts/application.html.erb
>          <%= link_to 'Sign in', user_session_path %>
- Remove logic from the view

2021-03-19 18:52 UTC, lekegitrepo commented on app/views/users/_user.html.erb
> +    <% end %>
- Remove logic from the view

2021-03-21 21:22 UTC, voscarmv requested changes
# Nice work so far. 👍 
- In a clean install of your project I was able to set up two accounts, and send a friend request from account No. 1 to account No. 2. Good work there.
- Good work with the changes requested by the previous TSE.

## However, there are some changes required 👀 🧰 🔨 🔧 
- When I tried logging into account No. 2 to see the friend request, I was not able to find a button anywhere that would allow me to accept it. The only button that appears on account No. 1's username after I sent them my friend request, is the "Request friendship" button. There should be a different button that says something like "Accept pending friendship". Please fix this so that I can accept friendship requests.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-03-22 07:55 UTC, mke2111 approved these changes
# STATUS: APPROVED 🥇  🟡 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

- [ ] [OPTIONAL] It's best practice to exclude any kind of logic in any of the files in the views folder. You have a few logic statements in the files there. Transfer them to the helpers folder and create methods for them.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

2021-03-22 10:12 UTC, merged